version: '3.3'

services:
{% if cookiecutter.use_mailhog == 'y' %}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    logging:
      driver: none
{% endif %}

{% if cookiecutter.use_redis == 'y' %}
  redis:
    image: redis
    hostname: redis
    ports:
      - 6379:6379
{% endif %}

