version: '3.3'

services:
{% if cookiecutter.use_mailhog == 'y' %}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    logging:
      driver: none
{% endif %}

{% if cookiecutter.use_elastic_search == 'y' %}
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data

{% endif %}

{% if cookiecutter.use_redis == 'y' %}
  redis:
    image: redis
    hostname: redis
    ports:
      - 6379:6379
{% endif %}

{% if cookiecutter.use_celery == 'y' %}
  beat:
    build:
      context:  ./backend
    volumes:
        - ./backend:/app
    command: celery -A config beat
    env_file: .env

  worker:
    build: 
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
        - rabbitmq
        - redis
    command: celery -A config worker --loglevel=info
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - RABBITMQ_HOST=mq
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=secret
      - AWS_ACCESS_KEY_ID=AKIAQANJB6P56XJUVF45
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=crop-rx-local-web
      - DEPLOYMENT_ENVIRONMENT=local
      - LOCAL_HOST=TRUE
      - AWS_HTTPS=NO
      - AWS_VIRTUAL_HOSTING=FALSE
      - WEB_HOST=backend
      - ELASTICSEARCH_CONN=http://es01:9200
      - DB_AUTH_KEY=f1b4fd36382857784f87ec4cfea17f18572333cd

  mq:
    image: rabbitmq:latest
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - 5672:5672
      - 15672:15672

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://user:secret@mq:5672//
      - FLOWER_PORT=5555
    ports:
      - 5555:5555

{% endif %}

{% if cookiecutter.use_selenium %}
selenium:
  image: selenium/standalone-chrome-debug:3.7.1
  ports:
    - 4444:4444
    - 5900:5900

{% endif %}

volumes:
  {% if  cookiecutter.use_elastic_search == 'y' %}
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  {% endif %}


