version: '3.3'

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    environment: 
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - RABBITMQ_HOST=mq
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=secret
      - AWS_ACCESS_KEY_ID=AKIAQANJB6P56XJUVF45
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=crop-rx-local-web
      - DEPLOYMENT_ENVIRONMENT=local
      - LOCAL_HOST=TRUE
      - AWS_HTTPS=NO
      - AWS_VIRTUAL_HOSTING=FALSE
      - WEB_HOST=backend
      - FRONTEND_URL=http://localhost:8080/
      - CELERY_TASK_ALWAYS_EAGER=False
      - ELASTICSEARCH_CONN=http://es01:9200
      - DB_AUTH_KEY=f1b4fd36382857784f87ec4cfea17f18572333cd
     
  
  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: {}
 